"""add system prompt fields to judgements

Revision ID: 0273ad411757
Revises: df011612feca
Create Date: 2025-10-23 13:10:51.755171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0273ad411757'
down_revision: Union[str, Sequence[str], None] = 'df011612feca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgements', sa.Column('system_prompt_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('judgements', sa.Column('values_file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_judgements_system_prompt_type'), 'judgements', ['system_prompt_type'], unique=False)
    op.create_index(op.f('ix_judgements_values_file_name'), 'judgements', ['values_file_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judgements_values_file_name'), table_name='judgements')
    op.drop_index(op.f('ix_judgements_system_prompt_type'), table_name='judgements')
    op.drop_column('judgements', 'values_file_name')
    op.drop_column('judgements', 'system_prompt_type')
    # ### end Alembic commands ###
