"""add values_md table

Revision ID: 31cf3d9c5179
Revises: 7d3f08a41425
Create Date: 2025-10-29 20:15:26.411228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31cf3d9c5179'
down_revision: Union[str, Sequence[str], None] = '7d3f08a41425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('values_md',
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('markdown_text', sa.Text(), nullable=False),
    sa.Column('structured_json', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('judgement_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('participant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values_md')
    # ### end Alembic commands ###
