"""add repetition_number to judgements

Revision ID: 72380a526f84
Revises: 0273ad411757
Create Date: 2025-10-23 14:12:44.556568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72380a526f84'
down_revision: Union[str, Sequence[str], None] = '0273ad411757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgements', sa.Column('repetition_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_judgements_repetition_number'), 'judgements', ['repetition_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judgements_repetition_number'), table_name='judgements')
    op.drop_column('judgements', 'repetition_number')
    # ### end Alembic commands ###
