"""add collection and batch_id to dilemmas

Revision ID: 7d3f08a41425
Revises: 72380a526f84
Create Date: 2025-10-29 12:32:14.004313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3f08a41425'
down_revision: Union[str, Sequence[str], None] = '72380a526f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dilemmas', sa.Column('collection', sa.String(), nullable=True))
    op.add_column('dilemmas', sa.Column('batch_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_dilemmas_batch_id'), 'dilemmas', ['batch_id'], unique=False)
    op.create_index(op.f('ix_dilemmas_collection'), 'dilemmas', ['collection'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dilemmas_collection'), table_name='dilemmas')
    op.drop_index(op.f('ix_dilemmas_batch_id'), table_name='dilemmas')
    op.drop_column('dilemmas', 'batch_id')
    op.drop_column('dilemmas', 'collection')
    # ### end Alembic commands ###
