"""add values_md_history and last_change_type

Revision ID: cb897d568b66
Revises: 2c02ae2a35b7
Create Date: 2025-11-23 17:39:27.641480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb897d568b66'
down_revision: Union[str, Sequence[str], None] = '2c02ae2a35b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('values_md_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('markdown_text', sa.Text(), nullable=False),
    sa.Column('structured_json', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('judgement_count', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_values_md_history_change_type'), 'values_md_history', ['change_type'], unique=False)
    op.create_index(op.f('ix_values_md_history_changed_at'), 'values_md_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_values_md_history_participant_id'), 'values_md_history', ['participant_id'], unique=False)
    op.add_column('values_md', sa.Column('last_change_type', sa.String(), server_default='ai_generated', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('values_md', 'last_change_type')
    op.drop_index(op.f('ix_values_md_history_participant_id'), table_name='values_md_history')
    op.drop_index(op.f('ix_values_md_history_changed_at'), table_name='values_md_history')
    op.drop_index(op.f('ix_values_md_history_change_type'), table_name='values_md_history')
    op.drop_table('values_md_history')
    # ### end Alembic commands ###
