"""Initial schema with dilemmas and judgements tables

Revision ID: df011612feca
Revises: 
Create Date: 2025-10-23 11:15:48.868428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df011612feca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dilemmas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('difficulty_intended', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dilemmas_created_at'), 'dilemmas', ['created_at'], unique=False)
    op.create_index(op.f('ix_dilemmas_created_by'), 'dilemmas', ['created_by'], unique=False)
    op.create_index(op.f('ix_dilemmas_difficulty_intended'), 'dilemmas', ['difficulty_intended'], unique=False)
    op.create_index(op.f('ix_dilemmas_parent_id'), 'dilemmas', ['parent_id'], unique=False)
    op.create_index(op.f('ix_dilemmas_title'), 'dilemmas', ['title'], unique=False)
    op.create_table('judgements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dilemma_id', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('judge_type', sa.String(), nullable=False),
    sa.Column('judge_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('choice_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('variation_key', sa.String(), nullable=True),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judgements_choice_id'), 'judgements', ['choice_id'], unique=False)
    op.create_index(op.f('ix_judgements_created_at'), 'judgements', ['created_at'], unique=False)
    op.create_index(op.f('ix_judgements_dilemma_id'), 'judgements', ['dilemma_id'], unique=False)
    op.create_index(op.f('ix_judgements_experiment_id'), 'judgements', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_judgements_judge_id'), 'judgements', ['judge_id'], unique=False)
    op.create_index(op.f('ix_judgements_judge_type'), 'judgements', ['judge_type'], unique=False)
    op.create_index(op.f('ix_judgements_mode'), 'judgements', ['mode'], unique=False)
    op.create_index(op.f('ix_judgements_temperature'), 'judgements', ['temperature'], unique=False)
    op.create_index(op.f('ix_judgements_variation_key'), 'judgements', ['variation_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judgements_variation_key'), table_name='judgements')
    op.drop_index(op.f('ix_judgements_temperature'), table_name='judgements')
    op.drop_index(op.f('ix_judgements_mode'), table_name='judgements')
    op.drop_index(op.f('ix_judgements_judge_type'), table_name='judgements')
    op.drop_index(op.f('ix_judgements_judge_id'), table_name='judgements')
    op.drop_index(op.f('ix_judgements_experiment_id'), table_name='judgements')
    op.drop_index(op.f('ix_judgements_dilemma_id'), table_name='judgements')
    op.drop_index(op.f('ix_judgements_created_at'), table_name='judgements')
    op.drop_index(op.f('ix_judgements_choice_id'), table_name='judgements')
    op.drop_table('judgements')
    op.drop_index(op.f('ix_dilemmas_title'), table_name='dilemmas')
    op.drop_index(op.f('ix_dilemmas_parent_id'), table_name='dilemmas')
    op.drop_index(op.f('ix_dilemmas_difficulty_intended'), table_name='dilemmas')
    op.drop_index(op.f('ix_dilemmas_created_by'), table_name='dilemmas')
    op.drop_index(op.f('ix_dilemmas_created_at'), table_name='dilemmas')
    op.drop_table('dilemmas')
    # ### end Alembic commands ###
