/// <reference path="../worker-configuration.d.ts" />
/// <reference types="astro/client" />

// Cloudflare bindings/secrets are typed by wrangler types — see
// worker-configuration.d.ts (regenerated by `pnpm cf-typegen`).
//
// Runtime access:
//   import { env } from 'cloudflare:workers';
